### ISSUE TITLE
nn_recvmsg/nn_sendmsg

### ISSUE THREAD

**Issue by SebastianEdwards** [chuckremes/nn-core#4]
Hello,

I've been using this library for a month or so and it's really fantastic! I'm now trying to implement RAW REQREP sockets and I'm getting a bit lost when it comes to using nn_recvmsg (which I've noted you don't recommend, but this appears to be required to get message headers.)

Just wondering if you had any example code that might help illustrate how to use RAW REQREP sockets or nn_recvmsg/nn_sendmsg in general.

**Comment by SebastianEdwards** [comment]
Actually, I think what I actually need is an nn_device. Have opened pull request #5 to add support for this.

**Comment by chuckremes** [comment]
Cool, thanks!
