### ISSUE TITLE
Submit a new version to RubyGems

### ISSUE THREAD

**Issue by richardgill** [chuckremes/nn-core#6]
We're using you're bleeding edge version and putting a stable version into RubyGems would be greatly appreciated :smile:

**Comment by fbernier** [comment]
@chuckremes I'd be willing to do this next time if you want to give rubygems access.

**Comment by chuckremes** [comment]
@fbernier Yes, I'll add you. Send me the email address that you use for ruby gems and I'll update the owner list.

**Comment by fbernier** [comment]
@richardgill 0.3.0 has been released to rubygems. Cheers!

**Comment by richardgill** [comment]
Thanks very much :+1:
